### ISSUE TITLE
Add package fio to list of packages

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#92]
We're using `fio` more and more for validation/testing purposes. One of the things we'd like to do is run a validation script to insure that bandwidth to storage (NetApp) is acceptable before handoff to customer. Given our other uses of `fio`, this is a natural tool to use.

Can `fio` be pre-installed on our SLES images?

And if so: `fio` isn't a standard package on the SLES 12 DVD, so it doesn't appear to be on the standard SMT repos. Is there an extended SMT repo where `fio` is available? If so, what's the URI for that repo that I should add?

Thanks guys.

**Comment by rjschwei** [comment]
> We're using `fio` more and more for validation/testing purposes. One of the things we'd like to do is run a validation script to insure that bandwidth to storage (NetApp) is acceptable before handoff to customer. Given our other uses of `fio`, this is a natural tool to use.
> 
> Can `fio` be pre-installed on our SLES images?

Not at the moment for SLES 12 SP3 based images. The tool is part of SUSE Enterprise Storage, but is also available in the SLES base distribution in SLE 15. I will file a feature request and see if we can get it added to SLE 12 as well.

> 
> And if so: `fio` isn't a standard package on the SLES 12 DVD, so it doesn't appear to be on the standard SMT repos. Is there an extended SMT repo where `fio` is available? If so, what's the URI for that repo that I should add?

No, the only way to get it for SLE 12 ATM would be form the openSUSE Build service, i.e. no support, or getting it form SES (SUSE Enterprise Storage). However, SES is not part of the SAP product and thus this is not accessible.

**Comment by schaefi** [comment]
> I will file a feature request and see if we can get it added to SLE 12 as well.

Thanks Robert

So as this does not exist for sle12 we can only wait for the request to get processed. @jeffaco if you need it earlier you can use the ```packages:``` section in the config file and put the package as you need it on the lun. However with that approach we are out of maintenance/warranty

Setting the blocked label and keep this one open

**Comment by schaefi** [comment]
Per log on the image build:

```
r15 | rjschwei | 2019-02-21 17:44:44 | 25729304e254f9f27316447c29c4e926 | 1.0.2 | 

- Add fio, now available as update
```

Fixed on 12 SP4

**Comment by rjschwei** [comment]
Sorry, not yet resolved I was pulled away in the middle of theis. Adding fio created dependency issues. SO for the next test image build we might want to remove this again. It's never as easy as one thinks at first ;)

**Comment by schaefi** [comment]
Interesting because the image build itself did not outline any dependency issue and just built. The image sent to Jeff also contains fio. I'm sure you will explain further details to me once you get to it ;)

**Comment by jeffaco** [comment]
Latest SP4 image appears to have `fio` installed, although I didn't actually try to run it yet.

**Comment by rjschwei** [comment]
> Interesting because the image build itself did not outline any dependency issue and just built. The image sent to Jeff also contains fio. I'm sure you will explain further details to me once you get to it ;)

I had to modify the project config to deal with the dependency issue. So this is something that still needs to be sorted out in the production build project. Which is also why I did not add fio to the SLE 15 build.

**Comment by rjschwei** [comment]
Images on their way to production.
